commongrounds/commongrounds/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('merchstore/', include('merchstore.urls')),
    #path('localevents/', include('localevents.urls')),
    #path('bookclub/', include('bookclub.urls')),
    #path('diyprojects/', include('diyprojects.urls')),
    #path('commissions/', include('commissions.urls')),
]

commongrounds/diyprojects/urls.py
from django.urls import path
from django.shortcuts import redirect
from .views import ProjectListView, ProjectDetailView


urlpatterns = [
    path('', lambda request: redirect('project_list')),
    path('projects', ProjectListView.as_view(), name='project_list'),
    path('project/<int:pk>', ProjectDetailView.as_view(), name='project_detail'),
]

commongrounds/diyprojects/models.py
from django.db import models


class ProjectCategory(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']
        verbose_name_plural = "project categories"


class Project(models.Model):
    title = models.CharField(max_length=255)
    category = models.ForeignKey(ProjectCategory, on_delete=models.SET_NULL, null=True)
    description = models.TextField()
    materials = models.TextField()
    steps = models.TextField()
    created_on = models.DateTimeField(auto_now=False, auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True, auto_now_add=False)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-created_on']
        verbose_name_plural = "projects"

commongrounds/diyprojects/views.py
from .models import ProjectCategory, Project
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView


class ProjectListView(ListView):
    model = ProjectCategory
    template_name = 'diyprojects/project_list.html'

    def get_queryset(self):
        return ProjectCategory.objects.prefetch_related('project_set').all()


class ProjectDetailView(DetailView):
    model = Project
    template_name = 'diyprojects/project_detail.html'

commongrounds/diyprojects/templates/diyprojects/base.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{% block title %}{% endblock %}</title>
</head>
<body>
    {% block body %}
    {% endblock %}
</body>
</html>

commongrounds/diyprojects/templates/diyprojects/project_detail.html
{% extends 'diyprojects/base.html' %}

{% block title %}{{project.title}}{% endblock %}

{% block body %}
    <a href="{% url 'project_list'%}">
        <li>Back to Project List</li>
    </a>
    <h2>{{project.title}}</h2>
    <p><b>Category: </b>{{project.category.name}}</p>
    <p><b>Materials: </b>{{project.materials}}</p>
    <p><b>Steps: </b>{{project.steps}}</p>
    <b>Created on: </b>{{project.created_on}} <br>
    <b>Last updated on: </b>{{project.updated_on}}
{% endblock %}

commongrounds/diyprojects/templates/diyprojects/project_list.html
{% extends 'diyprojects/base.html' %}

{% block title %}Project List{% endblock %}

{% block body %}
    <h1>Project List</h1>
    <hr>
    {% for category in projectcategory_list %}
        <h2>{{category}}</h2>
        <p>{{category.description}}</p> 
        <p><b>Projects under this category: </b></p>
        <ul>
            {% for project in category.project_set.all %}
                <a href="{% url 'project_detail' project.pk %}">
                <li>{{project}}</li>
                </a>
            {% empty %}
                <li>No projects in this category.</li>
            {% endfor %}
        </ul>
        <hr>
    {% endfor %}
{% endblock %}